### ISSUE TITLE
Build fails on Windows

### ISSUE THREAD

**Issue by blueridanus** [SecondHalfGames/jolt-rust#4] opened 2024-06-01 04:40 UTC
```
   Compiling joltc-sys v0.3.1+Jolt-5.0.0
error: failed to run custom build command for `joltc-sys v0.3.1+Jolt-5.0.0`

Caused by:
  process didn't exit successfully: `C:\Users\davip\Projects\rust-jolt\target\debug\build\joltc-sys-789cf4edbfdbd6d1\build-script-build` (exit code: 101)
  --- stdout
  CMAKE_TOOLCHAIN_FILE_x86_64-pc-windows-msvc = None
  CMAKE_TOOLCHAIN_FILE_x86_64_pc_windows_msvc = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-pc-windows-msvc = None
  CMAKE_GENERATOR_x86_64_pc_windows_msvc = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-pc-windows-msvc = None
  CMAKE_PREFIX_PATH_x86_64_pc_windows_msvc = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-pc-windows-msvc = None
  CMAKE_x86_64_pc_windows_msvc = None
  HOST_CMAKE = None
  CMAKE = None
  running: "cmake" "C:\\Users\\davip\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\joltc-sys-0.3.1+Jolt-5.0.0\\JoltC" "-G" "Visual Studio 17 2022" "-Thost=x64" "-Ax64" "-DCMAKE_INSTALL_PREFIX=C:\\Users\\davip\\Projects\\rust-jolt\\target\\debug\\build\\joltc-sys-83f219ca7c79a97a\\out" "-DCMAKE_C_FLAGS= -nologo -MD -Brepro" "-DCMAKE_C_FLAGS_RELEASE= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS= /EHsc -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS_RELEASE= /EHsc -nologo -MD -Brepro" "-DCMAKE_ASM_FLAGS= -nologo -MD -Brepro" "-DCMAKE_ASM_FLAGS_RELEASE= -nologo -MD -Brepro" "-DCMAKE_BUILD_TYPE=Release" "-DINTERPROCEDURAL_OPTIMIZATION=OFF"
  -- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.22631.
  -- Configuring done (0.0s)
  -- Generating done (0.1s)
  -- Build files have been written to: C:/Users/davip/Projects/rust-jolt/target/debug/build/joltc-sys-83f219ca7c79a97a/out/build
  running: "cmake" "--build" "." "--target" "install" "--config" "Release" "--parallel" "28"
  MSBuild version 17.10.4+10fbfbf2e for .NET Framework

    cmake_pch.cxx
  C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\immintrin.h(105,13): error C2220: the following warning is treated as an error [C:\Users\davip\Projects\rust-jolt\target\debug\build\joltc-sys-83f219ca7c79a97a\out\build\JoltPhysics\Build\Jolt.vcxproj]
  C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\immintrin.h(105,13): warning C4514: '__check_isa_support': unreferenced inline function has been removed [C:\Users\davip\Projects\rust-jolt\target\debug\build\joltc-sys-83f219ca7c79a97a\out\build\JoltPhysics\Build\Jolt.vcxproj]
  C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\immintrin.h(118,1): warning C4514: '__check_isa_avx10_512': unreferenced inline function has been removed [C:\Users\davip\Projects\rust-jolt\target\debug\build\joltc-sys-83f219ca7c79a97a\out\build\JoltPhysics\Build\Jolt.vcxproj]
  C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\include\immintrin.h(125,13): warning C4514: '__check_arch_support': unreferenced inline function has been removed [C:\Users\davip\Projects\rust-jolt\target\debug\build\joltc-sys-83f219ca7c79a97a\out\build\JoltPhysics\Build\Jolt.vcxproj]

  --- stderr
  thread 'main' panicked at C:\Users\davip\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cmake-0.1.50\src\lib.rs:1098:5:

  command did not execute successfully, got: exit code: 1

  build script failed, must exit now
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
(following the upstream [build instructions](https://github.com/jrouwe/JoltPhysics/blob/master/Build/README.md) works just fine)

**Comment by LPGhatguy** [comment] 2024-10-14 18:35
Hey, sorry for the delay in responding here! We're starting work on this library again after focusing elsewhere for a bit, we'll look into this.

**Comment by LPGhatguy** [comment] 2024-10-18 02:08
So far, I'm not able to reproduce this error on my Windows machine or on the CI runners.

The Jolt Physics 5.1.0 patch notes mention one of the warnings you're seeing being escalated to an error: https://github.com/jrouwe/JoltPhysics/releases/tag/v5.1.0

It's possible that this all might be fixed by just upgrading our pinned version of Jolt to 5.1.0. We have an open issue for this in SecondHalfGames/JoltC#12 and will be doing this soon.

**Comment by LPGhatguy** [comment] 2024-10-18 02:10
Actually, hah, scratch that, the GitHub CI runners for JoltC are having the same issue.
![image](https://github.com/user-attachments/assets/a855344e-6f7b-4dc4-832a-d64fe99585dd)

It must be something to do with newer MSVC versions that have now hit the runners, but haven't affected me since I haven't upgraded yet. I'll look into this tonight.

**Comment by LPGhatguy** [comment] 2024-10-18 02:42
![windows builds now working, linux builds newly broke](https://github.com/user-attachments/assets/dd095f49-e340-4b41-be09-38959da4c872)
![xkcd 'success'](https://github.com/user-attachments/assets/1b072427-dbcb-4ba8-8695-0e97c889d3b1)

**Closed** 2024-10-18 03:10 UTC
Labels: bug
